In [1034]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import cross_val_score

In [1035]:
train= pd.read_csv(r'C:\Users\Gaurav Kesari\Playstore App Downloads Prediction\train.csv')

# train = train.drop(['Downloads'], axis=1)
print(train.shape)
train.head()

(16516, 11)

,Offered_By,Category,Rating,Reviews,Size,Price,Content_Rating,Last_Updated_On,Release_Version,OS_Version_Required,Downloads
0,ps_id-24654,Finance,4.18,1481,Varies with device,Free,Everyone,May 05 2020,Varies with device,Varies with device,"100,000+"
1,ps_id-35329,Music And Audio,4.81,302,10M,Free,Everyone,Mar 26 2020,3.9.18,4.1 and up,"5,000+"
2,ps_id-11044,Game Casual,4.27,374,27M,Free,Everyone,May 01 2020,1.10.1,4.1 and up,"10,000+"
3,ps_id-36068,Business,4.03,122058,Varies with device,Free,Teen,May 02 2020,Varies with device,Varies with device,"10,000,000+"
4,ps_id-35831,Medical,4.60,358,Varies with device,297.5742,Everyone,Nov 29 2018,Varies with device,Varies with device,"5,000+"

In [1036]:
test = pd.read_csv(r'C:\Users\Gaurav Kesari\Playstore App Downloads Prediction\test.csv')
print(test.shape)
test.head()

(24776, 10)

,Offered_By,Category,Rating,Reviews,Size,Price,Content_Rating,Last_Updated_On,Release_Version,OS_Version_Required
0,ps_id-18231,Game Puzzle,4.52,1362,36M,Free,Everyone,May 05 2020,1.4.1,4.0.3 and up
1,ps_id-1874,Shopping,4.29,3353,Varies with device,Free,Teen,May 05 2020,Varies with device,Varies with device
2,ps_id-3182,Photography,4.55,161855,Varies with device,Free,Everyone,May 05 2020,Varies with device,Varies with device
3,ps_id-31452,Game Action,3.97,545,16M,Free,Everyone,Dec 07 2016,2,4.1 and up
4,ps_id-25641,Photography,4.65,1672,33M,Free,Everyone,Jan 25 2020,1,4.4 and up

In [1037]:
data = pd.concat([train, test], ignore_index=True)
data.nunique()

Offered_By             36772
Category                  51
Rating                   347
Reviews                18724
Size                     703
Price                    129
Content_Rating             6
Last_Updated_On         2012
Release_Version         8052
OS_Version_Required       37
Downloads                 18
dtype: int64

In [1038]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41292 entries, 0 to 41291
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Offered_By           41292 non-null  object
 1   Category             41292 non-null  object
 2   Rating               41292 non-null  float64
 3   Reviews              41292 non-null  int64
 4   Size                 41292 non-null  object
 5   Price                41292 non-null  object
 6   Content_Rating       41292 non-null  object
 7   Last_Updated_On      41292 non-null  object
 8   Release_Version      41292 non-null  object
 9   OS_Version_Required  41292 non-null  object
 10  Downloads            16516 non-null  object
dtypes: float64(1), int64(1), object(9)
memory usage: 3.5+ MB

In [1039]:
data.isnull().sum(), data.shape

(Offered_By                 0
 Category                   0
 Rating                     0
 Reviews                    0
 Size                       0
 Price                      0
 Content_Rating             0
 Last_Updated_On            0
 Release_Version            0
 OS_Version_Required        0
 Downloads              24776
 dtype: int64,
 (41292, 11))

In [1040]:
test['Release_Version'].value_counts()

Varies with device    2342
1                      989
1.1                    563
1.2                    447
1.3                    344
                      ...
6.3.33                   1
1.0.7.a                  1
3.6.0.28                 1
1.0.0.44                 1
1.45.0                   1
Name: Release_Version, Length: 5681, dtype: int64

In [1041]:
data.head()

,Offered_By,Category,Rating,Reviews,Size,Price,Content_Rating,Last_Updated_On,Release_Version,OS_Version_Required,Downloads
0,ps_id-24654,Finance,4.18,1481,Varies with device,Free,Everyone,May 05 2020,Varies with device,Varies with device,"100,000+"
1,ps_id-35329,Music And Audio,4.81,302,10M,Free,Everyone,Mar 26 2020,3.9.18,4.1 and up,"5,000+"
2,ps_id-11044,Game Casual,4.27,374,27M,Free,Everyone,May 01 2020,1.10.1,4.1 and up,"10,000+"
3,ps_id-36068,Business,4.03,122058,Varies with device,Free,Teen,May 02 2020,Varies with device,Varies with device,"10,000,000+"
4,ps_id-35831,Medical,4.60,358,Varies with device,297.5742,Everyone,Nov 29 2018,Varies with device,Varies with device,"5,000+"

In [1042]:

from sklearn.preprocessing import LabelEncoder
min=10
Release = (data['Release_Version'].value_counts()<min)

combine = [train, test]
l= LabelEncoder()
for dataset in combine:
    dataset['Category_code']=l.fit_transform(dataset['Category'])
    dataset['Content_Rating_code'] = l.fit_transform(dataset['Content_Rating'])
    dataset['Price_code'] = l.fit_transform(dataset['Price'])
#   dataset['Last_Updated_On_code'] = l.fit_transform(dataset['Last_Updated_On'])
    dataset['OS_Version_Required_code'] = l.fit_transform(dataset['OS_Version_Required'])
#     dataset['Size_code'] = l.fit_transform(dataset['Size'])
    dataset['Last_Updated_On_year']=dataset['Last_Updated_On'].str.split(' ', expand=True)[2].astype(int)
    dataset['Last_Updated_On_month']=dataset['Last_Updated_On'].str.split(' ', expand=True)[0]
    dataset['Last_Updated_On_date']=dataset['Last_Updated_On'].str.split(' ', expand=True)[1].astype(int)
    dataset['Offered_By_id']=dataset['Offered_By'].str.split('-', expand=True)[1].astype(int)
    dataset['Size']=dataset['Size'].str.replace('Varies with device', '20.26480988132722')
    dataset['Size']= dataset['Size'].str.split('M', expand=True)[0]
    dataset['Size']= dataset['Size'].apply(lambda x:'1' if 'k' in x else x).astype(float)
    dataset['Release_Version']=dataset['Release_Version'].apply(lambda x: '0' if Release.loc[x]==True else x)
    dataset['Release_Version']=l.fit_transform(dataset['Release_Version'])   
    dataset['Rating*Reviews']=dataset['Rating']*dataset['Reviews']
mean = train.Size.dropna().mean()
print(mean)    
for dataset in combine:    
    dataset['Last_Updated_On_month_code']=l.fit_transform(dataset['Last_Updated_On_month'])
# train['Size']=train['Size'].float.replace('0.0', '20.26480988132722')
# test['Size']=test['Size'].float.replace('0.0', '20.26480988132722')    
    
# train['Downloads_code'] = l.fit_transform(train['Downloads'])

22.618158473746494

In [1043]:
train.head()

,Offered_By,Category,Rating,Reviews,Size,Price,Content_Rating,Last_Updated_On,Release_Version,OS_Version_Required,...,Category_code,Content_Rating_code,Price_code,OS_Version_Required_code,Last_Updated_On_year,Last_Updated_On_month,Last_Updated_On_date,Offered_By_id,Rating*Reviews,Last_Updated_On_month_code
0,ps_id-24654,Finance,4.18,1481,20.26481,Free,Everyone,May 05 2020,521,Varies with device,...,12,1,82,26,2020,May,5,24654,6190.58,8
1,ps_id-35329,Music And Audio,4.81,302,10.00000,Free,Everyone,Mar 26 2020,0,4.1 and up,...,38,1,82,15,2020,Mar,26,35329,1452.62,7
2,ps_id-11044,Game Casual,4.27,374,27.00000,Free,Everyone,May 01 2020,58,4.1 and up,...,21,1,82,15,2020,May,1,11044,1596.98,8
3,ps_id-36068,Business,4.03,122058,20.26481,Free,Teen,May 02 2020,521,Varies with device,...,4,4,82,26,2020,May,2,36068,491893.74,8
4,ps_id-35831,Medical,4.60,358,20.26481,297.5742,Everyone,Nov 29 2018,521,Varies with device,...,37,1,43,26,2018,Nov,29,35831,1646.80,9

In [1044]:
test.head()

,Offered_By,Category,Rating,Reviews,Size,Price,Content_Rating,Last_Updated_On,Release_Version,OS_Version_Required,Category_code,Content_Rating_code,Price_code,OS_Version_Required_code,Last_Updated_On_year,Last_Updated_On_month,Last_Updated_On_date,Offered_By_id,Rating*Reviews,Last_Updated_On_month_code
0,ps_id-18231,Game Puzzle,4.52,1362,36.00000,Free,Everyone,May 05 2020,116,4.0.3 and up,24,1,94,18,2020,May,5,18231,6156.24,8
1,ps_id-1874,Shopping,4.29,3353,20.26481,Free,Teen,May 05 2020,521,Varies with device,44,4,94,36,2020,May,5,1874,14384.37,8
2,ps_id-3182,Photography,4.55,161855,20.26481,Free,Everyone,May 05 2020,521,Varies with device,42,1,94,36,2020,May,5,3182,736440.25,8
3,ps_id-31452,Game Action,3.97,545,16.00000,Free,Everyone,Dec 07 2016,195,4.1 and up,15,1,94,21,2016,Dec,7,31452,2163.65,2
4,ps_id-25641,Photography,4.65,1672,33.00000,Free,Everyone,Jan 25 2020,3,4.4 and up,42,1,94,25,2020,Jan,25,25641,7774.80,4

In [1045]:
train= train.drop(['Offered_By', 'Last_Updated_On', 'Last_Updated_On_month', 'Release_Version', 'Category', 'Price', 'Content_Rating', 'OS_Version_Required'], axis=1)

In [1046]:
test =test.drop(['Offered_By', 'Last_Updated_On', 'Last_Updated_On_month', 'Release_Version', 'Category', 'Price', 'Content_Rating', 'OS_Version_Required'], axis=1)

In [1047]:
# train['Rating']=pd.qcut(train['Rating'], 6)

In [1048]:
# train['Rating']

In [1049]:
#  pip install --user --upgrade tensorflow-gpu

In [1050]:
from sklearn.preprocessing import OneHotEncoder
# from sklearn.compose import ColumnTransformer 

# columnTransformer = ColumnTransformer([('encoder', OneHotEncoder())], remainder='passthrough') 
  
# y = np.array(columnTransformer.fit_transform(train['Downloads']), dtype = np.str) 

# data = np.array(columnTransformer.fit_transform(data), dtype = np.str)
# train['Downloads'] = train['Downloads'].str.replace('+','')
# train['Downloads'] = train['Downloads'].str.replace(',','').astype(float).astype(int)
# train['Downloads'] = train['Downloads'].map({'10': 'a', '50': 'b', '100': 'c', '500': 'd', '1000': 'e', '5000': 'f', '10000': 'g', '50000': 'h', '100000': 'i', '500000': 'j', '1000000': 'k', '5000000': 'l', '10000000': 'm', '50000000': 'n', '100000000': 'o', '500000000': 'p', '1000000000': 'q', '5000000000': 'r'}).astype(str)

# train['Downloads']= l.fit_transform(train['Downloads'])



# train['Downloads']=l.fit_transform(train['Downloads'])
y= train['Downloads']




# OHE= OneHotEncoder(sparse=False)
# y= pd.DataFrame(OHE.fit_transform(train[['Downloads']]))
# y.index = train.index
# y=train['Downloads']
# y= y.str.replace('+', '')
# y= y.str.replace(',','')

# y = y.map({'10': 0, '50': 1, '100': 2, '500': 3, '1000': 4, '5000': 5, '10000': 6, '50000': 7, '100000': 8, '500000': 9, '1000000': 10, '5000000': 11, '10000000': 12, '50000000': 13, '100000000': 14, '500000000': 15, '1000000000': 16, '5000000000': 17}).astype(float)


# from keras.utils import to_categorical

# encoded = to_categorical(y)


X= train.drop(['Downloads'], axis=1)
# y.reshape(-1,1)
y

0            100,000+
1              5,000+
2             10,000+
3         10,000,000+
4              5,000+
             ...
16511      1,000,000+
16512         10,000+
16513        500,000+
16514    100,000,000+
16515        100,000+
Name: Downloads, Length: 16516, dtype: object

In [1051]:
# y.value_counts()

In [1052]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16516 entries, 0 to 16515
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Rating                      16516 non-null  float64
 1   Reviews                     16516 non-null  int64
 2   Size                        16516 non-null  float64
 3   Category_code               16516 non-null  int32
 4   Content_Rating_code         16516 non-null  int32
 5   Price_code                  16516 non-null  int32
 6   OS_Version_Required_code    16516 non-null  int32
 7   Last_Updated_On_year        16516 non-null  int32
 8   Last_Updated_On_date        16516 non-null  int32
 9   Offered_By_id               16516 non-null  int32
 10  Rating*Reviews              16516 non-null  float64
 11  Last_Updated_On_month_code  16516 non-null  int32
dtypes: float64(3), int32(8), int64(1)
memory usage: 1.0 MB

In [1053]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24776 entries, 0 to 24775
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Rating                      24776 non-null  float64
 1   Reviews                     24776 non-null  int64
 2   Size                        24776 non-null  float64
 3   Category_code               24776 non-null  int32
 4   Content_Rating_code         24776 non-null  int32
 5   Price_code                  24776 non-null  int32
 6   OS_Version_Required_code    24776 non-null  int32
 7   Last_Updated_On_year        24776 non-null  int32
 8   Last_Updated_On_date        24776 non-null  int32
 9   Offered_By_id               24776 non-null  int32
 10  Rating*Reviews              24776 non-null  float64
 11  Last_Updated_On_month_code  24776 non-null  int32
dtypes: float64(3), int32(8), int64(1)
memory usage: 1.5 MB

In [1054]:
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split

train_X, val_X, train_y, val_y = train_test_split(X, y, random_state=1)

In [1055]:
# !pip install lightgbm

In [1056]:
from sklearn.ensemble import StackingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import BaggingClassifier
from lightgbm import LGBMClassifier

bag=BaggingClassifier(n_estimators=100,max_features=12)
lgb=LGBMClassifier(n_estimators=100,num_leaves=48,reg_lambda=50,reg_alpha=20)
etc=ExtraTreesClassifier(n_estimators=100,max_depth=26,min_samples_split=2,max_features=12)

In [1057]:
estimators=[("bag",bag),("lgb",lgb),("etc",etc)]
reg = StackingClassifier(estimators=estimators)

In [1060]:
scores=cross_val_score(reg, X,y, cv = 5, scoring = "accuracy")
scores.mean()

E:\Anacond\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
E:\Anacond\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
E:\Anacond\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
E:\Anacond\lib\site-packages\sklearn\model_selection\_validation.py:901: RuntimeWarning: Number of classes in training fold (17) does not match total number of classes (18). Results may not be appropriate for your use case. To fix this, use a cross-validation technique resulting in properly stratified folds
  warnings.warn('Number of classes in training fold ({}) does '
E:\Anacond\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
E:\Anacond\lib\site-packages\sklearn\model_selection\_validation.py:901: RuntimeWarning: Number of classes in training fold (17) does not match total number of classes (18). Results may not be appropriate for your use case. To fix this, use a cross-validation technique resulting in properly stratified folds
  warnings.warn('Number of classes in training fold ({}) does '
E:\Anacond\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
E:\Anacond\lib\site-packages\sklearn\model_selection\_validation.py:901: RuntimeWarning: Number of classes in training fold (17) does not match total number of classes (18). Results may not be appropriate for your use case. To fix this, use a cross-validation technique resulting in properly stratified folds
  warnings.warn('Number of classes in training fold ({}) does '
E:\Anacond\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
E:\Anacond\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
E:\Anacond\lib\site-packages\sklearn\model_selection\_validation.py:901: RuntimeWarning: Number of classes in training fold (17) does not match total number of classes (18). Results may not be appropriate for your use case. To fix this, use a cross-validation technique resulting in properly stratified folds
  warnings.warn('Number of classes in training fold ({}) does '
E:\Anacond\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
E:\Anacond\lib\site-packages\sklearn\model_selection\_validation.py:901: RuntimeWarning: Number of classes in training fold (17) does not match total number of classes (18). Results may not be appropriate for your use case. To fix this, use a cross-validation technique resulting in properly stratified folds
  warnings.warn('Number of classes in training fold ({}) does '
E:\Anacond\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
E:\Anacond\lib\site-packages\sklearn\model_selection\_validation.py:901: RuntimeWarning: Number of classes in training fold (17) does not match total number of classes (18). Results may not be appropriate for your use case. To fix this, use a cross-validation technique resulting in properly stratified folds
  warnings.warn('Number of classes in training fold ({}) does '
E:\Anacond\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
E:\Anacond\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
E:\Anacond\lib\site-packages\sklearn\model_selection\_validation.py:901: RuntimeWarning: Number of classes in training fold (17) does not match total number of classes (18). Results may not be appropriate for your use case. To fix this, use a cross-validation technique resulting in properly stratified folds
  warnings.warn('Number of classes in training fold ({}) does '
E:\Anacond\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
E:\Anacond\lib\site-packages\sklearn\model_selection\_validation.py:901: RuntimeWarning: Number of classes in training fold (17) does not match total number of classes (18). Results may not be appropriate for your use case. To fix this, use a cross-validation technique resulting in properly stratified folds
  warnings.warn('Number of classes in training fold ({}) does '
E:\Anacond\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
E:\Anacond\lib\site-packages\sklearn\model_selection\_validation.py:901: RuntimeWarning: Number of classes in training fold (17) does not match total number of classes (18). Results may not be appropriate for your use case. To fix this, use a cross-validation technique resulting in properly stratified folds
  warnings.warn('Number of classes in training fold ({}) does '
E:\Anacond\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
E:\Anacond\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
E:\Anacond\lib\site-packages\sklearn\model_selection\_validation.py:901: RuntimeWarning: Number of classes in training fold (17) does not match total number of classes (18). Results may not be appropriate for your use case. To fix this, use a cross-validation technique resulting in properly stratified folds
  warnings.warn('Number of classes in training fold ({}) does '

E:\Anacond\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
E:\Anacond\lib\site-packages\sklearn\model_selection\_validation.py:901: RuntimeWarning: Number of classes in training fold (17) does not match total number of classes (18). Results may not be appropriate for your use case. To fix this, use a cross-validation technique resulting in properly stratified folds
  warnings.warn('Number of classes in training fold ({}) does '
E:\Anacond\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
E:\Anacond\lib\site-packages\sklearn\model_selection\_validation.py:901: RuntimeWarning: Number of classes in training fold (17) does not match total number of classes (18). Results may not be appropriate for your use case. To fix this, use a cross-validation technique resulting in properly stratified folds
  warnings.warn('Number of classes in training fold ({}) does '
E:\Anacond\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.5710222528642609

In [1061]:
reg.fit(X,y)
predictions=reg.predict_proba(test)
print(reg.score(X,y))

E:\Anacond\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
E:\Anacond\lib\site-packages\sklearn\model_selection\_validation.py:901: RuntimeWarning: Number of classes in training fold (17) does not match total number of classes (18). Results may not be appropriate for your use case. To fix this, use a cross-validation technique resulting in properly stratified folds
  warnings.warn('Number of classes in training fold ({}) does '
E:\Anacond\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
E:\Anacond\lib\site-packages\sklearn\model_selection\_validation.py:901: RuntimeWarning: Number of classes in training fold (17) does not match total number of classes (18). Results may not be appropriate for your use case. To fix this, use a cross-validation technique resulting in properly stratified folds
  warnings.warn('Number of classes in training fold ({}) does '
E:\Anacond\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
E:\Anacond\lib\site-packages\sklearn\model_selection\_validation.py:901: RuntimeWarning: Number of classes in training fold (17) does not match total number of classes (18). Results may not be appropriate for your use case. To fix this, use a cross-validation technique resulting in properly stratified folds
  warnings.warn('Number of classes in training fold ({}) does '
E:\Anacond\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.9679704528941633

In [1062]:

# from xgboost import XGBClassifier



# model_xgbregressor=XGBClassifier(n_estimators=100)
# model_xgbregressor.fit(X,y)
# predictions=model_xgbregressor.predict_proba(test)
# print(model_xgbregressor.score(X,y))

In [1063]:
# from sklearn.tree import DecisionTreeRegressor

# lr=DecisionTreeRegressor()
# lr.fit(X,y)
# predictions=lr.predict(test)
# print(lr.score(X,y))

In [1064]:
# from sklearn.ensemble import RandomForestClassifier

# rf = RandomForestClassifier(n_estimators=100)
# rf.fit(X,y)
# predictions=rf.predict_proba(test)
# print(rf.score(X,y))

In [1065]:
output=pd.DataFrame(predictions)
# output= output.astype('str') + '+'
# from sklearn.preprocessing import OneHotEncoder



# OHE= OneHotEncoder(handle_unknown='ignore', sparse=False)
# y= pd.DataFrame(OHE.fit_transform(output))
output.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,0.000239,0.014611,0.000138,0.000163,0.068059,0.000342,0.000214,0.650411,0.000301,0.000781,0.001116,0.000038,0.000159,0.193522,0.000146,0.000224,0.069388,0.000152
1,0.000158,0.076588,0.000182,0.000219,0.010454,0.001224,0.000285,0.655013,0.000515,0.000380,0.003888,0.000047,0.000219,0.038049,0.000237,0.000269,0.212047,0.000227
2,0.000296,0.032607,0.000471,0.000192,0.000299,0.811490,0.000259,0.000144,0.006970,0.000246,0.127830,0.000043,0.000184,0.000228,0.017264,0.000250,0.000336,0.000891
3,0.000969,0.005972,0.000205,0.000241,0.158854,0.000470,0.000364,0.480468,0.000400,0.002006,0.000941,0.000053,0.000219,0.318642,0.000257,0.000370,0.029332,0.000238
4,0.000245,0.015480,0.000154,0.000187,0.075884,0.000425,0.000241,0.631888,0.000335,0.000635,0.001262,0.000041,0.000185,0.217909,0.000180,0.000225,0.054549,0.000176

In [1066]:
output.to_csv('my_submission.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!